spring.application.name=sb-ecom
#For local
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=zohra

##For AWS
#spring.datasource.url=jdbc:postgresql://e-commercedb.cz2cqm4qwfpa.eu-north-1.rds.amazonaws.com/myapp
#spring.datasource.username=TaquiDB
#spring.datasource.password=Spring13

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#project folder for image
project.file=images/

spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
spring.app.jwtcookie=springBootEcom

Frontned.URL=http://localhost:5173

#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG
# needed if you deploy on elastic beanstack
#server.port=5000